name: Build and Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main  # change if your branch name is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.4'   # 👈 specify exact version
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web --release
        
      - name: Test GH_PAT secret
        run: |
          if [ -z "${{ secrets.GH_PAT }}" ]; then
           echo "GH_PAT is not set!"
           exit 1
          else
           echo "GH_PAT secret exists and is accessible."
           fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: build/web
